### PR TITLE
Euler, Quaternion: fix compiler errors for GCC 6.1.1

### PR DESCRIPTION
**Pull request by bkueng**
GCC output:
error: implicit conversion from ‘float’ to ‘double’ to match other operand
of binary expression [-Werror=double-promotion]

### CODE REVIEW

**Comment by LorenzMeier** [comment]
CI fail

**Comment by bkueng** [comment]
Style issue. The output could really be more informative.

**Comment by bkueng** [comment]
@tumbili can you please review, merge & update the submodules in Firmware repo?

**Comment by jgoppert** [comment]
Looks good to me.

**Pull request merged**
