### PR TITLE
Add slicing tests that are not pure row slicing

### PR DESCRIPTION
**Pull request by madcowswe**
I had a look at the implementation of `slice`, and I found it odd that it doesn't have a copy loop. The current implementation does a raw memcpy of the underlying contiguous row-major data. As far as I can tell, this could only slice along rows. Interestingly, I found that the tests only tested for slicing along rows, so this bug would go unnoticed.

I added some tests that checks slicing along columns also. I have a feeling this would break, and we need to fix the implementation of `slice`. However I could be wrong, and hence I'm submitting these tests first to verify.

### CODE REVIEW

**Comment by madcowswe** [comment]
I had a look at the output of the tests on Travis, and indeed `slice` is broken.
I would suggest to replace the memcpy implementation with an explicit copy-loop.

**Comment by jgoppert** [comment]
Thanks for finding this. Please format the code if you get a chance so travis passes.

**Comment by madcowswe** [comment]
Sorry do you mean I should create the code for a working `slice` implementation, or do you mean that the formatting of my provided test-code is not adequate?

**Comment by MaEtUgR** [comment]
@madcowswe nice catch! btw you can also run the tests on your machine, see https://github.com/PX4/Matrix#testing

**Comment by TSC21** [comment]
I also did this test yesterday and found it was not working. I feel we need to get something similar to what the `Block` implementation is doing in Eigen.

**Comment by jgoppert** [comment]
I feel like we could do a check if the fast row access is valid, if not, switch to a slower for loop approach.

**Comment by madcowswe** [comment]
I don't see how using `memcpy` is faster than a copy loop on a platform like ARM Cortex, likely `memcpy` would actually be implemented as a copy loop. In fact, a copy loop on floats would be able to copy full 32-bit words at a time, while `memcpy` is done with bytes, and could therefore even be slower.

My recommendation is to discard the `memcpy` implementation and replace it with a 2D copy loop.

**Comment by mhkabir** [comment]
@bkueng Thoughts on performance?

**Comment by jgoppert** [comment]
Some info on memcpy: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka3934.html, we should probably just test on hardware. Either way, having a working for loop version should be priority to get this bug fixed.

**Comment by madcowswe** [comment]
Ah yeah it looks like the compiler would be able to choose a 32 bit version of `memcpy`. Still, since this is a header library, it's likely that a copy loop would just be inlined or at least very optimised.

**Comment by bkueng** [comment]
> Some info on memcpy: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka3934.html, we should probably just test on hardware. Either way, having a working for loop version should be priority to get this bug fixed.

I agree with that. `memcpy` is generally heavily optimized and uses the fastest instructions possible. However branching adds penalties too, and for the small matrices we are using it for, a loop is probably fine.

**Comment by TSC21** [comment]
@jgoppert @bkueng @MaEtUgR can we agree then on an approach that helps fixing this?

**Comment by madcowswe** [comment]
I implemented slice with a copy loop. It mirrors the implementation of `set` right below it. Seems to pass the tests. 
Though I don't know what the format error is about on the GCC build.

**Comment by bkueng** [comment]
Can you check CI?

```
checking format...
Error: need to format
```

**Comment by TSC21** [comment]
@madcowswe if you have time, please run `make format` and then commit again.

**Comment by TSC21** [comment]
@MaEtUgR can you please fix rhe trailing ws then?

**Comment by MaEtUgR** [comment]
Done: https://github.com/PX4/Matrix/commit/56b069956da141da244926ed7000e89b2ba6c731

**Comment by TSC21** [comment]
Perfect

**Pull request merged**
