### PR TITLE
Added hexagon support

### PR DESCRIPTION
**Pull request by mcharleb**
These changes are required for hexagon support.

### CODE REVIEW

**Comment by mcharleb** [comment]
@jgoppert  The change I made should not affect the Linux build at all. Are you sure the failing test worked previously?

**Comment by jgoppert** [comment]
Weird, master did pass, have had travis ci up for awhile now. Please investigate further failing attitude test if you have time.

**Comment by jgoppert** [comment]
I tested this branch locally and it had no problems, so I'm merging it.

**Comment by jgoppert** [comment]
Ah, this pull request was made against the quaternion branch which they never got to pass the unit tests. I will try to fix it.

**Pull request merged**
