### PR TITLE
add DCM renormalize method

### PR DESCRIPTION
**Pull request by kd0aij**
@jgoppert It seemed like adding this method here made sense when I was rebasing https://github.com/PX4/Firmware/pull/5498 to deal with the elimination of Euler angles from the vehicle attitude setpoint topic. Let me know if you think it should go somewhere else.

### CODE REVIEW

**Comment by jgoppert** [comment]
Looks good. Please add a unit test for it.

**Comment by kd0aij** [comment]
should I also run "make format"? Will cause a lot of whitespace changes.

**Comment by kd0aij** [comment]
I added a unit test in systemcmds/tests: https://github.com/PX4/Firmware/pull/5785 and tested.
But it's not clear how to add one here and build/run it.

**Comment by jgoppert** [comment]
@kd0aij Here is how to run the testing/formatting:

```bash
git clone git@github.com:PX4/Matrix
mkdir build
cd build
cmake .. -DFORMAT=ON -DTESTING=ON
make format
make coverage
make test
ctest -V
```

**Comment by jgoppert** [comment]
@kd0aij Please add a test here: https://github.com/PX4/Matrix/blob/master/test/attitude.cpp#L98

**Comment by kd0aij** [comment]
@jgoppert "make coverage" fails with an incomprehensible error message, but the new test runs OK
"make format" changed every file in matrix/matrix but I only committed the files which I had edited.

**Comment by jgoppert** [comment]
Closing in favor of #32.

**Pull request closed without merging**
